### ISSUE TITLE
Immersive Farm 2 incompatibility 

### ISSUE THREAD

**Issue by fishytunacan** [Himetarts/Always-Raining-in-the-Valley#1]
im pretty new to mods and saw your progress in a facebook group. I finally got to get all the mods and it made my farm layout glitch like crazy and reverted the layout to the original layout. Im not sure where it fights eachother.

**Comment by Himetarts** [comment]
Hi there! ARV doesn't change any maps, so it's rather impossible for it to
have anything to do with IFR2. I'm unsure of why you're having the issue,
but ARV is most likely not the place to look for it ):
